routes:
  route-1:
    port: 443
    address: 'https://aligoren.com'
    type: header
    headers:
      type:
        values:
          - blog
  route-2:
    port: 443
    address: 'https://www.google.com.tr'
    type: header
    headers:
      type:
        values:
          - google
  route-3:
    port: 443
    address: 'https://twitter.com'
    type: header
    headers:
      type:
        values:
          - twitter
  route-4:
    port: 443
    address: 'https://github.com'
    type: path
    paths:
      - '/github'